/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.unina.techweb.controller.api;

import com.unina.techweb.dto.AuthenticationDto;
import com.unina.techweb.dto.CustomerDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-05-26T10:55:43.493411474+02:00[Europe/Rome]")
@Validated
@Tag(name = "auth", description = "the auth API")
public interface AuthApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /auth/login : Effettua l&#39;operazione di login
     *
     * @param customerDto Le informazioni dell&#39;utente (required)
     * @return Login effettuato con successo (status code 200)
     */
    @Operation(
        operationId = "login",
        summary = "Effettua l'operazione di login",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Login effettuato con successo", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthenticationDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/login",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthenticationDto> login(
        @Parameter(name = "CustomerDto", description = "Le informazioni dell'utente", required = true) @Valid @RequestBody CustomerDto customerDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"expiresIn\" : 0.8008281904610115, \"token\" : \"token\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /auth/register : Consente all&#39;utente di registarsi
     *
     * @param customerDto Le informazioni dell&#39;utente (required)
     * @return Login effettuato con successo (status code 200)
     */
    @Operation(
        operationId = "register",
        summary = "Consente all'utente di registarsi",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Login effettuato con successo", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthenticationDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/register",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthenticationDto> register(
        @Parameter(name = "CustomerDto", description = "Le informazioni dell'utente", required = true) @Valid @RequestBody CustomerDto customerDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"expiresIn\" : 0.8008281904610115, \"token\" : \"token\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
