version: '4.0'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_HOST: ${API_HOST:-localhost}
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      API_HOST: ${API_HOST:-localhost}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    networks:
      - app-network
      - back-network
    environment:
      API_HOST: ${API_HOST:-localhost}

  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - back-network

networks:
  app-network:
    driver: bridge
  back-network:

volumes:
  postgres_data:
